---
## Create a LVM Volume Group

- name: Create a LVM
  hosts: all
  become: yes

  tasks:
    - name: Create LVM volume group
      lvg: 
        vg: vg1
        pvs: /dev/sda1
        pezise: 32

## Create a Logical Volume

    - name: Create a Logical Volume
      lvol: 
      vg: vg1
      lv: lvol1
      pvs: /dev/sda1
---
## Managing File Systems

    - name: Create a filesystem
      filesystem:
        fstype: xfs
        dev: /dev/vg1/lvol1

    - name: Mount a filesystem
      mount: 
        fstype: xfs
        src: /dev/vg1/lvol1
        path: /opt/web
        state: mounted
        

    
