---

- name: Common Modules Playbook
  become: yes
  hosts: webservers

  tasks:
   - name: Install httpd on webservers
     yum:
      name: httpd
      state: present

   - name: Start and enable httpd
     service:
      name: httpd
      state: started
      enabled: yes
   
   - name: Create index.html
     file:
      path: /var/www/html/index/html
      state: touch 